#! /bin/bash

sxhkd &
polybar bar &

bspc monitor -d 1 2 3 4 5

bspc config border_width         4
bspc config window_gap          12
bspc config focused_border_color $grn
bspc config normal_border_color $bg
bspc config presel_feedback_color $grn

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on

# Panel
# panel &
