#! /bin/bash

bspc monitor -d dev ter web org mus doc
source $HOME/bin/export_colors $(color_theme_name)

bspc config border_width         3
bspc config window_gap          0
bspc config focused_border_color $grn
bspc config normal_border_color $bg
bspc config presel_feedback_color $grn
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config focus_follows_pointer true
bspc config single_monocle false

bspc rule --remove '*'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox-esr desktop='^3' state=tiled follow=on
bspc rule -a Firefox-esr:Dialog desktop='^3' state=floating follow=on
bspc rule -a Emacs desktop='^4' state=tiled follow=on
bspc rule -a Gvim desktop='^1' state=tiled follow=on

polybar bar &

